import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Map from '../components/Map'

export default function Home() {
  return (
    <>
      <Head>
        <title>Expo Line</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content='width=device-width, initial-scale=1' />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <header className={styles.header}> Expo Line 🚆</header>
        <Map/>
        <myfooter className={styles.myFooter}>🚄 Translink 🚍</myfooter>
      </main>

    </>
  )
}
